server:
  port: 8060
spring:
  application.name: rental-service
  profiles.active: prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mvc:
    format:
      date: dd/MM/yyyy
